
---
- name: ios facts
  hosts: ios
  connection: network_cli 
  gather_facts: true
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: admin
    ansible_password: cisco  
  tasks:

    - name: merge provide configuration with device configuration
      cisco.ios.ios_command:
        commands: show version
    - name: Configure the login banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          this is my login banner
          that contains a multiline
          string
        state: present
