
---
- name: ios facts
  hosts: 10.0.137.143
  connection: network_cli 
  gather_facts: true
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: admin
    ansible_password: cisco  
  tasks:

    - name: Merge provided configuration with device configuration
      cisco.ios.ios_l3_interfaces:
        config:
        - name: Ethernet1/0
          ipv4:
          - address: 192.168.0.1/24
        state: merged

    - name: Turn on interfaces
      cisco.ios.ios_interfaces:
        config:
        - name: Ethernet1/0
          description: configured by ansible yest
          enabled: true
        state: merged
    
    - name: save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified
