---

- name: Deploy NTP Configuration
  connection: network_cli
  gather_facts: false
  hosts: routers

  vars:
    ntp1: "10.10.10.10"
    ntp2: "20.20.20.20"
  
  tasks:

    - name: Configure NTP on all Devices
      # section need to be fix
      ios_config:
        lines:
          - ntp server {{item}}

      with_items:
        - "{{ntp1}}"
        - "{{ntp2}}" 


    - name: Verifiy NTP configuration
      # section need to be fix
      ios_command:
        commands: show ntp config
      register: result

    - name: Display NTP Config to Screen
      debug: var=result.stdout_lines

      
       