---
- name: ios facts
  hosts: ios
  connection: local
  tasks: 
    - name: gather ios facts
      ios_facts:
        provider:
          port: 22
          authorize: yes
          auth_pass: cisco
          username: admin
          password: cisco

    - name: what is the ios os ver ?
      debug:
        var: ansible_net_version

    - name: what is the hostname ?
      debug:
        var: ansible_net_hostname


